### ISSUE TITLE
Forward compatability of Event/Request tagged unions

### ISSUE THREAD

**Issue by ifreund** [ifreund/zig-wayland#14]
Currently our Event/Request tagged unions are not forward compatible with newer protocol versions. Ideally zig would allow defining non-exhaustive tagged unions, but it does not yet. We should make a proposal outlining the use-case for this feature and consider alternative ways to handle forward compatibility in the meantime.

**Comment by ifreund** [comment]
As an alternative, we could make protocol object generic over their version. This might have a large negative effect on ergonomics however, needs investigation.

**Comment by ifreund** [comment]
I think an even better option would be to pass a max supported version as input to the scanner in the build.zig file. The scanner would then simply not generate code for newer events/requests/etc found in the xml.

**Comment by tadeokondrak** [comment]
> I think an even better option would be to pass a max supported version as input to the scanner in the build.zig file.

I like this idea. The core protocol (other than the trio of `wl_display`, `wl_registry`, and `wl_callback`) can change, though. Maybe the library should provide those three and the rest is generated per-project?
