### ISSUE TITLE
error: unused function parameter

### ISSUE THREAD

**Issue by averycoolbean** [ifreund/zig-wayland#22]
when trying to build river 
zig-wayland/src/scanner.zig causes an error at 995:13
```
error: unused function parameter
    options: std.fmt.FormatOptions,
    ^
```
i really dont know what any of this means cause i dont know jackshit about zig, or c++ or really normal c, nor do i want to deal with it at 2am rn, so i cant really give much more info than that

**Comment by novakne** [comment]
Looks like you're using zig master and not zig 0.8

**Comment by ifreund** [comment]
Yep, you are using zig master, that compiler error is not implement in the 0.8.0 zig compiler
