### ISSUE TITLE
error: unable to override alignment of packed struct fields

### ISSUE THREAD

**Issue by yujiri8** [ifreund/zig-wayland#39]
I was running the zig-hello-wayland example with zig 0.9.1 and it worked, but when updating to zig 0.10.0-dev.3577+b3922289b, trying to import this library gives me:
```zig
/home/yujiri/code/hello-zig-wayland/zig-cache/zig-wayland/xdg_shell_common.zig:42:69: error: unable to override alignment of packed struct fields
pub const ConstraintAdjustment = packed struct {slide_x: bool align(@alignOf(u32)) = false,slide_y: bool = false,flip_x: bool = false,flip_y: bool = false,resize_x: bool = false,resize_y: bool = false,_paddding6: bool = false,
                                                                    ^~~~~~~~~~~~~
```

**Comment by yujiri8** [comment]
Just removing the part that adds this align annotation seems to have made everything work for me, but I'm sure it's there for a reason, I just don't understand enough about it to know how to properly update it for 0.10.

**Comment by ifreund** [comment]
Zig 0.10 has not yet been released, it sounds like you are trying to use the zig master branch. This is not supported, only Zig 0.9.1 is supported.
