### ISSUE TITLE
ascii.spaces renamed to ascii.whitespace in zig 0.11

### ISSUE THREAD

**Issue by kdchambers** [ifreund/zig-wayland#42]
I know zig-wayland is targeting 0.10, but I'm using it in https://github.com/kdchambers/vkwayland and will be keeping my own fork in-sync with master zig. If you're interested in creating another zig-wayland branch for master zig I can push any changes I make back here.

**Comment by ifreund** [comment]
Hello, I don't plan on making a branch for compatibility with master zig until the 0.11 release is imminent. I use the latest zig release for all my projects to make packaging them for linux distributions possible and to save myself time/reduce code churn.

I don't have the time to help out with zig master branch compatibility at this time, sorry.
