### ISSUE TITLE
Error name is reserved

### ISSUE THREAD

**Issue by RossComputerGuy** [ifreund/zig-wayland#45]
In the scanner's `emitFn` method, it does not check if `message.name` is `error`. In my testing, it results in this error:
```
zig-cache/zig-wayland/wayland_client.zig:50:9: error: expected '(', found 'error'
}pub fn error(_display: *Display, _object_id:*common.Object, _code:u32, _message:[*:0]const u8) void {const _proxy = @ptrCast(*client.wl.Proxy,_display);const _args = [_]common.Argument{.{ .o = @ptrCast(*common.Object, _object_id) },.{ .u = _code},.{ .s = _message},};
```

**Comment by ifreund** [comment]
What zig wayland version are you using exactly? No version I know of generates that code.

**Comment by novakne** [comment]
I would guess that the code corresponding in the current `wayland_client.zig` is 
```zig
    pub const Event = union(enum) {
        @"error": struct {
            object_id: ?*common.Object,
            code: u32,
            message: [*:0]const u8,
        },
        delete_id: struct {
            id: u32,
        },
    };
```
Since it's seems to be a modified fork I'm guessing it's an error introduced in a commit not here, I'm not aware of any function with the name error

**Comment by ifreund** [comment]
@RossComputerGuy please do not report bugs with a modified fork without mentioning that you are using a modified fork.

In any case, zig keywords are now escaped when printing camelCase idenifiers as of d507189f623507981f4f5b6a0f8b21b12b9c07e4.
