### ISSUE TITLE
Generate all protocols in 1 step vs in separate steps

### ISSUE THREAD

**Issue by RossComputerGuy** [ifreund/zig-wayland#47]
I've noticed zig-wayland generates all protocols in a singular step. This is good for simplicity, however I think it would be nice to generate all protocols each in their own step. This is because the current master versions of Zig will print a summary and builds steps using multiple threads. It could be worth the performance to generate all protocols in their own steps. This means `ScanProtocolsStep.step` would act like a top-level step. I'm willing to work on the PR but I'd like to hear from you, ifreund, before doing this.

**Comment by ifreund** [comment]
This is not just good for simplicity but necessary to handle references to objects across protocols.

The bulid.zig integration will need to be rewritten when I update to Zig 0.11 which I believe has added the necessary functionality for zig-wayland to properly use the cache.
