### ISSUE TITLE
Hash to Zig cache

### ISSUE THREAD

**Issue by RossComputerGuy** [ifreund/zig-wayland#48]
I've noticed zig-wayland uses `zig-cache/zig-wayland` for dumping generated files in. I think it may be worth it to use the cache properly like the builtin steps do. `LibExeObjStep` has a function called `addCSourceFileSource` so there's likely a way to properly leverage the cache even with C code.

**Comment by ifreund** [comment]
The bulid.zig integration will need to be rewritten when I update to Zig 0.11 which I believe has added the necessary functionality for zig-wayland to properly use the cache. Until then I have no intention of changing the status quo.
