### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jcoonrod** [ifreund/zig-wayland#52]
Perhaps I just need more documentation? When I tried to build, I got:
johncoonrod@penguin:~/hello-zig-wayland$ zig build
/home/johncoonrod/hello-zig-wayland/build.zig:3:25: error: unable to load '/home/johncoonrod/hello-zig-wayland/deps/zig-wayland/build.zig': FileNotFound
const Scanner = @import("deps/zig-wayland/build.zig").Scanner;

**Comment by novakne** [comment]
So it seems it's about hello-zig-wayland, you need to run `git submodule update --init`
