### ISSUE TITLE
Feature request: generate Wayland C headers

### ISSUE THREAD

**Issue by ashpil** [ifreund/zig-wayland#53]
Hello,

I'm building my own wrapper around GLFW and am working on replacing its cmake build system with Zig. In order to do this, I need to replicate the Wayland cmake modules, which generate the Wayland C headers via `wayland-scanner client-header`. If I understand correctly, zig-wayland is not currently able to do this. Would this be within the scope of the library?

I am not actually interested in using Wayland from Zig, if that makes my intent clearer. I'd just like to use the Zig build system to expose the Wayland files to GLFW.

Thanks!

**Comment by ifreund** [comment]
Nope, generating C headers is not within scope, I see no reason to re-write wayland-scanner.

You might want to build wayland-scanner using zig or something like that depending on your exact use-case

**Comment by ashpil** [comment]
That makes sense, thanks for the quick reply!
