### ISSUE TITLE
requested global interface 'wl_surface' not found in provided protocol xml

### ISSUE THREAD

**Issue by LordMZTE** [ifreund/zig-wayland#55]
My build script is essentially identical to the example in the README, but with `scanner.generate("wl_surface", 6);` added and generally other protocols.
This results in this error:
```
run zig-wayland-scanner (wayland.zig): error: error(zig-wayland): requested global interface 'wl_surface' not found in provided protocol xml

run zig-wayland-scanner (wayland.zig): error: the following command exited with error code 1:
/home/lordmzte/dev/dotfiles/scripts/vinput/zig-cache/o/a09f1759a2aed27bbe782e009ffd115c/zig-wayland-scanner -o /home/lordmzte/dev/dotfiles/scripts/vinput/zig-cache/o/08535f3a8cc1578e9235d3aa971dd4be/wayland.zig -i /usr/share/wayland/wayland.xml -g wl_surface 6 -g wl_seat 4 -g wl_data_device_manager 3 
```

The `wl_surface` protocol, version 6 is contained in my distro's (Arch) `/usr/share/wayland/wayland.xml` file right above `wl_seat`, but zig-wayland claims it's missing.

**Comment by LordMZTE** [comment]
Some inspection of the scanner code seems to reveal that `wl_surface` is filtered out due to being a non-global, however it is referenced in the code generated for the `wl_data_device_manager` but not generated itself. Notably, `wayland.client.wl.DataDevice.Event` contains a tag of a struct type which contains `wayland.client.wl.Surface`. This type is missing in the generated code, leading to a compile error.

**Comment by novakne** [comment]
You don't need `scanner.generate("wl_surface", 6);` in your build.zig. The error you see is because you added this. 

As you saw this is only needed for global interface, and zig-wayland should throw an error if you forget about adding something with `scanner.generate()` so I would advise you to only add it after you get an error, if your not sure about global interface.

**Comment by ifreund** [comment]
For reference, `wl_surface` is a child of the `wl_compositor` global interface and adding `scanner.generate("wl_compositor", 6);` or similar should fix your problem.

Any suggestions on how to improve the documentation here are welcome. The Wayland protocol really doesn't make this easy to understand.
