### ISSUE TITLE
Mention that `addProtocolPath` requires an absolute path

### ISSUE THREAD

**Issue by squiddy** [ifreund/zig-wayland#9]
```zig
const scanner = ScanProtocolsStep.create(b, "zig-wayland/");
scanner.addProtocolPath("protocol/foobar.xml");
```

Looking at the README, I thought using relatives paths surely should work but it results in an error. The code itself mentions that these paths are absolute.

```zig
    /// Slice of absolute paths of protocol xml files to be scanned
    protocol_paths: std.ArrayList([]const u8),
```

I don't know the proper way to do this, therefore no PR from me. That's how I solved it currently.

```zig
    scanner.addProtocolPath(std.fs.path.resolve(
        b.allocator,
        &[_][]const u8{"deps/wlr-protocols/unstable/wlr-screencopy-unstable-v1.xml"},
    ) catch unreachable);
```

---

Nice work on the scanner step, works nicely here! :)

**Comment by ifreund** [comment]
Oh I actually just ran into this myself and already pushed a fix to master. Do relative paths work for you now?

**Comment by squiddy** [comment]
Heh, I must have pulled the latest master right before you pushed the fix then. Working nicely here, thank you.
